version: "3"
services:
  mongodb:
    container_name: mongodb-container
    image: mongo:3
    restart: always
    volumes:
      - ./data/mongodb:/data/db
    ports: 
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm start
    volumes: 
      - ./dist:/usr/dev/clean-node-api/dist
    ports: 
      - "5050:5050"
    links: 
      - mongodb